unnies_ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from admin_unnies import views
from django.conf.urls.static import static
from django.conf import settings
from userauth.views import login, register
from unnies.views import home, products, view_product, view_profile, cart

urlpatterns = [
    path('admin/', admin.site.urls),
    #auth
    path('adminUnnies/', views.adminUnniesLogin, name = 'adminUnniesLogin'),
    #own admins
    path('adminUnniesMain/', views.adminView, name = 'adminView'),
    path('addProduct/', views.addProduct, name = 'addProduct'),
    path('adminUnniesMain/viewProduct/', views.viewProduct, name = 'viewProduct'),
    path('adminUnniesMain/registerAdmin/', views.registerAdmin, name='registeradmin' ),
    path('adminUnniesMain/editProduct/<int:id>', views.editProduct, name='editProduct' ),
    path('adminUnniesMain/deleteProduct/<int:id>', views.deleteProduct, name='deleteProduct' ),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('', home, name = 'home' ),
    path('products/', products, name = 'products' ),
    path('viewproduct/<int:id>', view_product, name="view_product"),
    path('profile/', view_profile, name = 'view_profile'),
    path('cart/', cart, name = 'cart'),



] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from account.models import Account
from products.models import Product
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_qty = models.IntegerField(blank = False)
    total_price = models.DecimalField(max_digits=9, decimal_places=2)
    selected = models.BooleanField(default=False)

products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    types = [
        ('Album', 'Album'),
        ('Merchandise','Merchandise' ),
        ('Photobook', 'Photobook'),
        ('Fan lights', 'Fan lights'),
        ('Accessories', 'Accessories'),
        ('Pre-orders', 'Pre-orders'),

    ]
    title = models.CharField(max_length=200)
    product_type = models.CharField(max_length=50, choices = types, default = 'Merchandise')
    description = models.TextField(blank= True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default = 0)
    stocks = models.PositiveIntegerField(default = 0)
    is_active = models.BooleanField(default = True)
    is_featured = models.BooleanField(default = False)
    rating = models.IntegerField(blank = True, null = True)
    sold = models.PositiveIntegerField(blank = True, default = 0)
    # image = models.ImageField(upload_to=None, height_field=None, width_field=None)

    def __str__(self):
        return self.title
    


class Variation(models.Model):
    product_var = models.ForeignKey("Product", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    product_type = models.CharField(max_length=50)
    description = models.TextField(blank= True)
    stocks = models.PositiveIntegerField(default = 0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default = 0)
    is_active = models.BooleanField(default = True)
    rating = models.IntegerField(blank = True, null =True)
    sold = models.PositiveIntegerField(blank = True, default = 0)

    

class ImageModelProduct(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media/product/", height_field=None)

    def __str__(self):
        return self.product.title
    

unnies/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from .models import Cart


class CartForm(forms.ModelForm):
    
    class Meta:
        model = Cart
        fields = ("product_qty","total_price",)

products/forms.py
from django import forms
from .models import Product, ImageModelProduct

class ProductForm(forms.ModelForm):

    class Meta:

        model = Product
        fields = (  'title',
                    'description',
                    'product_type',
                    'price',
                    'stocks',
                    'is_active',
                    'is_featured',
                    )

class ImageForm(forms.ModelForm):
    class Meta:
        model = ImageModelProduct
        fields = ("image",)

cart/views.py
from django.shortcuts import render

# Create your views here.

unnies/views.py
import random
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from products.models import Product, ImageModelProduct
from userauth.models import Profile
from django.core.paginator import Paginator
from django.http import JsonResponse
from cart.models import Cart
from cart.forms import CartForm
# Create your views here.
@login_required(login_url='/login/')
def home(request):
    featured = Product.objects.all().filter(is_featured = True)
    images = ImageModelProduct.objects.all()
    sideContent = list(map(lambda x : x,Product.objects.all()))
    sideContent = random.sample(sideContent, 2)
    context = {
        'featured': featured,
        'images': images,
        'sideContent': sideContent,
    }
    return render(request, 'unnies/index.html', context)

@login_required(login_url='/login/')
def products(request):
    # Get all the Products
    product_types = Product.objects.all().values('product_type').distinct().order_by('product_type')

    #Get the Dropdown list of available types of Products
    product_types = [ p_type['product_type'] for p_type in product_types ]

    #Get Images of the Products
    images = ImageModelProduct.objects.all()

    if request.method == "GET":
        #Get the Type of Product Type
        product_type = request.GET.get('productType')

        if product_type == None or product_type == "All":
            products = Product.objects.all().order_by('title')

        else:
            products = Product.objects.all().filter(product_type = product_type)
            
        paginator = Paginator(products,10)
        page_number = request.GET.get('page')
        if page_number == None:
            page_number = 1
        page_obj = paginator.get_page(page_number)

    context= {
        'selected':product_type,
        'product_types': product_types,
        'page_obj' : page_obj,
        'images': images,
    }
    return render(request, 'unnies/products.html', context)

@login_required(login_url="/login/")
def view_product(request, id):
    product = get_object_or_404(Product, pk = id)
    images = ImageModelProduct.objects.all()
    context = {
        'product': product,
        'images': images,
    }
    if request.is_ajax():
        if request.method == 'POST':
            total_price = product.price*int(request.POST.get('qty'))
            product_qty = int(request.POST.get('qty'))
            cart_prod = Cart(user =request.user, product = product, total_price = total_price, product_qty = product_qty)
            cart_prod.save()
           

    return render(request, 'unnies/view.html', context)



@login_required(login_url="/login/")
def view_profile(request):
    # print(request.user)
    try:
        profile = Profile.objects.all().get(user=request.user)
    except:
        return redirect('home')
        #TODO: add some functionality in here, to tell admin to open regular account
    
    # print(profile.name)
    context = {
        'profile':profile,
    }
    return render(request, 'unnies/profile.html', context)

@login_required(login_url="/login/")
def cart(request):
    cart_products = Cart.objects.all().filter(user=request.user)
    print(cart_products)

    if request.is_ajax():
        if request.method == "POST":
            id = int(request.POST.get('prod_id'))
            c_product = Cart.objects.get(id=id)
            try:
                if(c_product.product_qty + 1 < c_product.product.stocks):
                    c_product.product_qty +=1
                    c_product.total_price = c_product.product_qty * c_product.product.price
                    c_product.save()
                    return JsonResponse({'success':'success', 'prod_qty': c_product.product_qty }, status = 200)
            except:
                return JsonResponse({'success':'error', 'prod_qty': c_product.product_qty }, status = 200)
                

    context = {
        'cart_products':cart_products, 
    }
    return render(request, 'unnies/cart.html', context)

unnies/templates/unnies/cart.html
{% extends 'unnies/base.html' %}
{% load static %}
{% block cart %}
    <div class="cc-modal">
        <div class="cc-form">
            <div>Card Information Form</div>
            <div class="cards-cc">
                <span>Accepted Cards</span>
                <img src="./images/cc-img/mastercard.png" alt="master">
                <img src="./images/cc-img/visa.jpg" alt="visa">
            </div>
            <div class="n-card">
                <label>Name on Card</label>
                <input type="text" name="name-card" placeholder="Dave Charm Bulaquena">
            </div>
            <div class="n-card">
                <label>Credit Card Number</label>
                <input name="cc-number" type="text" maxlength="16" placeholder="1111 2222 3333 4444" />
            </div>
            <div class="n-card">
                <label>Expiry Month</label>
                <input type="text" name="cc-month" placeholder="September">
            </div>
            <div class="t-card">
                <div class="t-c">
                    <label>Expiry Year</label>
                    <input type="text" name="cc-year" placeholder="2024" maxlength="4">
                </div>
                <div>
                    <label>CCV</label>
                    <input type="number" name="ccv" placeholder="324" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" type="number" maxlength="3">
                </div>
            </div>
            <div class="cards-cc">
                <div class="cancel-cc">Cancel</div>
                <div class="save-cc">Save</div>
            </div>
        </div>
    </div>
    <div class="check-out-modal">
        <div class="check-out-form">
            <div class="items-package">
                <div class="item-head">
                    <div class="total-items">Total Item/s : 1</div>
                    <div class="order-d">OrderID: <span class="order-id"></span></div>
                    <div class="p-method">
                        Payment Method : Credit Card
                    </div>
                    <div class="op-card">
                        <div class="v-card"><img> 1111-2222-2222-2222</div>
                        <span class="change">change</span>
                        <div class="modal-card">
                            <div class="m-card"><img> 1111-2222-2222-2222</div>
                            <div class="m-card"><img> 1111-2222-2222-2222</div>
                            <div class="m-card"><img> 1111-2222-2222-2222</div>
                        </div>
                    </div>
                </div>
                <div class="packages">
                    <!-- <div class="package-item">
                        <img src="./images/product-image/albums/bts/bts1.jpg">
                        <div class="package-title">
                            BTS- Dynamite- Album
                        </div>
                        <div class="package-price">
                            Price : 1200
                        </div>
                        <div class="package-qty">
                            Qty : 1
                        </div>
                        <div class="package-total">
                            Total: 1200
                        </div>
                    </div>
                    <div class="package-item">
                        <img src="./images/product-image/albums/bts/bts1.jpg">
                        <div class="package-title">
                            BTS- Dynamite- Album
                        </div>
                        <div class="package-price">
                            Price : 1200
                        </div>
                        <div class="package-qty">
                            Qty : 1
                        </div>
                        <div class="package-total">
                            Total: 1200
                        </div>
                    </div>
                    <div class="package-item">
                        <img src="./images/product-image/albums/bts/bts1.jpg">
                        <div class="package-title">
                            BTS- Dynamite- Album
                        </div>
                        <div class="package-price">
                            Price : 1200
                        </div>
                        <div class="package-qty">
                            Qty : 1
                        </div>
                        <div class="package-total">
                            Total: 1200
                        </div>
                    </div> -->
                </div>
            </div>
            <div class="package-info">
                <div class="total-price-ship">
                    <span class="t-price">Total Price : 4200</span>
                    <span class="sf">plus shipping fee</span>
                </div>
                <div class="sf">
                    Standard Shipping Fee : ₱100
                </div>
            </div>
            <div class="contact-info">
                <div class="c-info">
                    <label>Recipient Name :</label>
                    <input name="n" type="text" value="Dave Charm Bulaquena">
                </div>
                <div class="c-info">
                    <label>Contact Number :</label>
                    <input name="c" type="text" value="09267138677">
                </div>
                <div class="c-info">
                    <label>Delivery Address : </label>
                    <input name="a" type="text" value="#452 Talospatang, Malasiqui, Pangasinan">
                </div>
            </div>
            <div class="check-buttons">
                <div class="check-cancel">
                    Cancel
                </div>
                <div class="check-confirm">
                    Order
                </div>
            </div>
        </div>
    </div>

    <div class="cart-container">
        <div class="cart-head">
            <div class="cart-prod"> <input type="checkbox" name="select-all" id="select-all"> Product</div>
            <div> Unit Price</div>
            <div> Quantity</div>
            <div> Total Price</div>
            <div> Actions</div>
        </div>
        <div class="shopping-cart">
        {% for product in cart_products %}
             <form class="cart-item" action = "" method = "POST" data-cartId ="{{ product.id }}">
                {% csrf_token %}
                <div class="item-desc">
                    <input type="checkbox" name="select" {% if product.selected %}checked{% endif %}>
                    {% for images in product.product.imagemodelproduct_set.all %}
                        {% if forloop.first %}
                            <div class="item-pic"><img src="{{ images.image.url}}"></div>
                        {% endif %}
                    {% endfor %}
                    <div class="cart-item-name">{{ product.product.title }}</div>
                </div>
                <div class="unit-price">₱{{ product.product.price }}</div>
                <div class="unit-quantity">
                    <div class="q-button">
                        <button class="op minus-cart">-</button>
                        <div class="quantity">{{ product.product_qty }}</div>
                        <button class="op plus-cart">+</button>
                    </div>
                </div>
                <div class="total-price">₱{{product.total_price}}</div>
                <div class="remove">Delete</div>
            </form>
        {% endfor %}
            <!-- <div class="cart-item">
                <div class="item-desc">
                    <input type="checkbox" name="select">
                    <div class="item-pic"><img src="./images/product-image/albums/bts/bts1.jpg"></div>
                    <div class="cart-item-name">BTS -Dynamite Album</div>
                </div>
                <div class="unit-price">₱1200</div>
                <div class="unit-quantity">
                    <div class="q-button">
                        <button class="op minus-cart">-</button>
                        <div class="quantity">0</div>
                        <button class="op plus-cart">+</button>
                    </div>
                </div>
                <div class="total-price">₱1200</div>
                <div class="remove">Delete</div>
            </div> -->
        </div>
    </div>
    <div class="cart-foot">
        <div class="pay-method">
            <div>
                Payment Method :
            </div>
            <div class="sel">
                <span>▼</span>
                <select>
                    <option value="COD">COD</option>
                    <option value="Credit Card">Credit Card</option>
                </select>
            </div>
        </div>
        <div>
            Merchandise Subtotal: <span class="sub-total">₱0</span>
        </div>
        <div class="checkout">Check Out</div>
    </div>
    <script src="{% static 'resources/jquery-3.5.1.min.js' %}"></script>
    <script src=" {% static 'js/cart.js' %}"></script>

   
{% endblock cart %}

unnies/templates/unnies/index.html
{% extends 'unnies/base.html' %} {% block content %}
<!-- for log in
    <div class="log-modal">
        <div class="log-sign">
            <div class="welcome">
                <div class="welcome-sign">
                    Welcome to
                </div>
                <div class="logo-welcome">
                    Unnies
                </div>
                <div class="say">
                    Your trusted partner in K-Shopping
                </div>
                <div class="in-out">
                    <span>Have an account already?</span> <span class="in-out-but s">Log in here</span>
                </div>
            </div>
            <div class="form-sign-log">
                <div class="sign-container">
                    <div class="set-up">Set up your account. 1/6</div>
                    <div class="quest">
                        <div class="question">What is your Full Name?</div>
                        <input type="text" name="name" placeholder="Enter your name" class="input-sign">
                    </div>
                    <div class="buttons-sign">
                        <div class="back">Back</div>
                        <div class="next">Next</div>
                    </div>
                </div>
                <div class="confirmation">
                    <div class="log-text">Set up your account. Completed</div>
                    <div class="quest">
                        <div>Congratulations, You've Created Your Account</div>
                    </div>
                    <div class="buttons-sign">
                        <div class="log-in">Log In</div>
                    </div>
                </div>

                <div class="log-container">
                    <div class="log-text">Log In To Your Account</div>
                    <div class="log-form">
                        <label>Username</label>
                        <input type="text" name="username" placeholder="Username Here">
                        <label>Password</label>
                        <input type="password" name="password" placeholder="Password Here">
                    </div>
                    <div class="buttons-sign">
                        <div class="log-next">Log In</div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
<!-- for log in -->

<div class="main">
    <div class="container-box side-box">
        <div class="carousel-box">
            <!---Dynamic Start-->
            {% for featured in featured %} {% if forloop.first %}
            <div class="carousel-container">
                {% for image in featured.imagemodelproduct_set.all %} {% if forloop.first %}
                <img class="featured-photo" src="{{ image.image.url }}"> {% endif %} {% endfor %}
                <div class="left-click"></div>
                <div class="right-click"></div>

                <div class="caption">
                    <div class="title">{{ featured.title }}</div>
                    <div class="sale">UP to <span>40% off</span></div>
                    <a href="{% url 'view_product' featured.id %}">
                        <div class="act-button">Shop now</div>
                    </a>
                </div>
            </div>
            {% else %}
            <div class="carousel-container hide">
                {% for image in featured.imagemodelproduct_set.all %} {% if forloop.first %}
                <img class="featured-photo" src="{{ image.image.url }}"> {% endif %} {% endfor %}
                <div class="left-click"></div>
                <div class="right-click"></div>

                <div class="caption">
                    <div class="title">{{ featured.title }}</div>
                    <div class="sale">UP to <span>40% off</span></div>
                    <a href="{% url 'view_product' featured.id %}">
                        <div class="act-button">Shop now</div>
                    </a>
                </div>
            </div>
            {% endif %} {% endfor %} {% comment %} {% endcomment %}
        </div>
    </div>
    <div class="container-box side-box-2">
        <div class="container-side">
            {% for content in sideContent %}
            <div class="side-feature">
                {% for image in content.imagemodelproduct_set.all %} {% if forloop.first %}
                <img src="{{ image.image.url }}"> {% endif %} {% endfor %}
                <div class="caption">
                    <div class="title">{{ content.title }}</div>
                    <div class="act-button"><a href="{% url 'view_product' content.id %}">View Product</a></div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="main-foot">
    <div class="foot-content">
        <span>90 Days return</span>
        <span>if goods have problem</span>
    </div>
    <div class="foot-content">
        <span>Secure Payment</span>
        <span>100% Secure Payment</span>
    </div>
    <div class="foot-content">
        <span>24/7 Support</span>
        <span>Dedicated Support</span>
    </div>
</div>
{% endblock content %}

unnies/templates/unnies/products.html
{% extends 'unnies/base.html' %} {% block content %}
{% load static %}
<div class="product-container">
    <div class="row">
        <form class="select" action="" method="GET" id="product_type_form">
            <span>▼</span>
            <select name="productType">
                <!-- <option value ="album" selected>Album</option>
                <option value = "merchandise">Merchandise</option>
                <option value = "photobook">Photobook</option>
                <option value = "fanlight">Fan Lights</option>
                <option value = "accessories">Accessories</option> -->
                <option value = "All"> All Products</option>
                {% for product_type in product_types %}
                    {% if selected == product_type %}
                        <option value = "{{ product_type }}" selected>{{ product_type }}</option>
                        {% else %}
                        <option value = "{{ product_type }}">{{ product_type }}</option>
                    {% endif %}
                        
                {% endfor %}
            </select>
        </form>
    </div>

    <div class="products">
        <div class="product-type">
            <h2>{% if selected == None %} All {% else %}{{ selected }}{% endif %}</h2>
        </div>
        <div class="product-holder">
            {% for product in page_obj %}
                <a href="{% url 'view_product' product.id %}">
                    <div class="product-card">
                        {% for image in product.imagemodelproduct_set.all %}
                            {% if forloop.first %}
                                <img class="product-image" src="{{ image.image.url }}">
                            {% endif %}
                        {% endfor %}
                        <div class="product-name">{{ product.title }}</div>
                        <div class="product-price">₱{{ product.price }}</div>
                    </div>
                </a>
            {% endfor %}
            <!-- <div class="product-card">
                    <img class="product-image" src="./images/product-image/albums/bts/bts1.jpg">
                    <div class="product-name">BTS - Dynamite Album</div>
                    <div class="product-price">₱1200</div>
                </div>
                <div class="product-card">
                    <img class="product-image" src="./images/product-image/albums/bts/bts2.jpg">
                    <div class="product-name">BTS- Map of the Souls</div>
                    <div class="product-price">₱1100</div>
                </div>
                <div class="product-card">
                    <img class="product-image" src="./images/product-image/albums/bts/bts3.jpg">
                    <div class="product-name">BTS - Wings Album</div>
                    <div class="product-price">₱1150</div>
                </div>
                <div class="product-card">
                    <img class="product-image" src="./images/product-image/albums/twice/twice1.jpg">
                    <div class="product-name">TWICE- Eyes Wide Open</div>
                    <div class="product-price">₱1150</div>
                </div> -->
        </div>
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
            {% endif %}
        </span>
    </div>

</div>
<script src="{% static 'resources/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/products.js' %}"></script>
{% endblock content %}

unnies/templates/unnies/view.html
{% extends 'unnies/base.html' %} {% load static %} {% block content %}
<div class="view-body">
    <div class="gallery-container">
        <div class="view-photo">
            {% for images in product.imagemodelproduct_set.all %} {% if forloop.first %}
            <img src="{{ images.image.url }}"> {% endif %} {% endfor %}
        </div>
        <div class="gallery-photo">
            {% for images in product.imagemodelproduct_set.all %}
            <div class="var-photo">
                <img src="{{ images.image.url }}">
            </div>
            {% endfor %} {% comment %}
            <div class="var-photo">
                <img src="./images/product-image/merchandise/bp3var/3.jpg">
            </div>
            <div class="var-photo">
                <img src="./images/product-image/merchandise/bp3var/4.jpg">
            </div>
            <div class="var-photo">
                <img src="./images/product-image/merchandise/bp3var/5.jpg">
            </div> {% endcomment %}
        </div>
    </div>
    <div class="gallery-container descriptions">
        <div class="item-title" data-id="{{ product.id }}">
            {{product.title}}
        </div>
        <div class="item-status">
            <div class="solds-rate">
                {{product.sold}} Sold | <span class="stars">⋆⋆⋆⋆</span>
            </div>
        </div>
        <div class="item-price">
            ₱{{ product.price }}
        </div>
        {% comment %}
        <div class="variation">
            <div class="var-text">Variation</div>
            <div class="var">
                <div class="variation-select">
                    <span>▼</span>
                    <select>
                            <option>Color</option>
                        </select>
                </div>
                <div class="variation-select">
                    <span>▼</span>
                    <select>
                            <option>Color</option>
                        </select>
                </div>
            </div>
        </div> {% endcomment %}
        <div class="quantity-container">
            <div class="q-text">Quantity</div>
            <div class="q-button">
                <button class="op minus">-</button>
                <div class="quantity" name="quantity">1</div>
                <button class="op plus">+</button>
            </div>
            <div class="stocks">
                <div class="stock-text"><span class="stock-qty"> {{ product.stocks }} </span> piece/s available</div>
            </div>
        </div>
        {% if product.stocks == 0 %}
        <div class="out-of-stock">
            Out of Stock!
        </div>
        {% else %}
        <div class="add-cart">
            Add to Cart
        </div>
        {% endif %}

        <div class="product-description">
            <b>Product Description: </b>
            <br> &nbsp;&nbsp;&nbsp;&nbsp;{{ product.description }}
        </div>
    </div>
    <form class="add-form" method="POST" action"">
        {% csrf_token %}
    </form>
</div>
<script src="{% static 'resources/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/view_product.js' %}"></script>
{% endblock content %}